[package]
name = "folder-listener"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notify = "5.0.0"
reqwest = "0.11.13"
tokio = { version = "1", features = ["full"] }
urlencoding = "2.1.2"